version: "3.5"
services:
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - RABBITMQ_DEFAULT_VHOST=myvhost
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    restart: always 
